### ISSUE TITLE
Asset files missing

### ISSUE THREAD

**Issue by jpzimmer** [MrArnaudMichel/Projet_Pokemon#2]
Good morning,
I can't test the EP4-Change Map part : there are some asset files missing.
The error is :+1: FileNotFoundError: [Errno 2] No such file or directory: '../../assets/map/house_0.tmx'

Is it possible to have the asset files present in the video ?
Great thanks for your work.

**Comment by MrArnaudMichel** [comment]
Hello !

I'm sorry I forgot to commit the files from episode 5. Normally, all the files have been added!

Thank you so much for letting me know and for the support !

Arnaud
